[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#2B2B2B"
secondaryBackgroundColor = "#404040"
textColor = "#FFFFFF"